controllers:
    resource: ../src/Controller/
    type: attribute

search_results:
    path: '/search-results/{query}'
    controller: 'App\Controller\SearchController::searchResults'
    methods: ['GET']
    options:
        expose: true
